---
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
- name: start nginx
  service:
      name: nginx
      state: started

- name: Deploy new code
  copy:
    src: index.html
    dest: /var/www/html/index.nginx-debian.html